/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/global/Avatar.vue')['default']
    BrandInfo: typeof import('./components/global/BrandInfo.vue')['default']
    ChatArea: typeof import('./components/chat/chatArea.vue')['default']
    ChatList: typeof import('./components/chat/chatList.vue')['default']
    ContactCard: typeof import('./components/contact/contactCard.vue')['default']
    ContactCardModal: typeof import('./components/global/ContactCardModal.vue')['default']
    ContactList: typeof import('./components/contact/contactList.vue')['default']
    EchatLoading: typeof import('./components/global/echatLoading.vue')['default']
    EchatWelcome: typeof import('./components/global/echatWelcome.vue')['default']
    FeatureList: typeof import('./components/global/FeatureList.vue')['default']
    FriendCard: typeof import('./components/friend/FriendCard.vue')['default']
    FriendRequestItem: typeof import('./components/friend/FriendRequestItem.vue')['default']
    FriendRequestPanel: typeof import('./components/friend/FriendRequestPanel.vue')['default']
    GroupCard: typeof import('./components/contact/groupCard.vue')['default']
    MessageBubble: typeof import('./components/chat/Message/MessageBubble.vue')['default']
    OnlineBoard: typeof import('./components/chat/onlineBoard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./components/setting/settingsDialog.vue')['default']
    TagDialog: typeof import('./components/friend/TagDialog.vue')['default']
    UserSearchPanel: typeof import('./components/friend/UserSearchPanel.vue')['default']
    UserSearchResultCard: typeof import('./components/friend/UserSearchResultCard.vue')['default']
    VirtualMessageList: typeof import('./components/chat/VirtualMessageList.vue')['default']
  }
}
